pipeline {
  agent any

  environment {
    PROJECT_ID = "s-0-009988"
    REGION     = "asia-south1"
    SERVICE    = "my-cloudrun-service"
    REPO       = "docker-images"
    IMAGE      = "asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO/cloudrun"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Vire-cloud/nginx-deployment.git'
      }
    }

    stage('Authenticate GCP') {
      steps {
        withCredentials([file(credentialsId: 'service-account', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
          sh '''
            gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
            gcloud config set project $PROJECT_ID
          '''
        }
      }
    }

    stage('Push Image') {
      steps {
        sh '''
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t $IMAGE:$BUILD_NUMBER -f test/Dockerfile test/ 
          docker push $IMAGE:$BUILD_NUMBER
        '''
      }
    }

    stage('Deploy to Cloud Run') {
      steps {
        sh '''
         // gcloud run deploy $SERVICE \
           // --image $IMAGE:$BUILD_NUMBER \
           // --region $REGION \
           // --platform managed \
           // --allow-unauthenticated
        '''
      }
    }
  }
}
