apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx12!</title>
    </head>
    <body>
        <h1>Hello from ConfigMap!</h1>
        <p>This is served from a Kubernetes ConfigMap.</p>
    </body>
    </html>
